renode/renode-infrastructure

- src/Emulator/Cores/Arm-M/CortexM.cs
- src/Emulator/Cores/Arm/Arm.cs
- src/Emulator/Cores/PowerPC/PowerPc.cs
- src/Emulator/Cores/PowerPC/PowerPc64.cs
- src/Emulator/Cores/RiscV/RiscV32.cs
- src/Emulator/Cores/RiscV/RiscV64.cs
- src/Emulator/Cores/Sparc/Sparc.cs
- src/Emulator/Cores/X86/X86.cs
- src/Emulator/Extensions/Utilities/GDB/Commands/QueryCommand.cs
- src/Emulator/Extensions/Utilities/GDB/Commands/ReadRegisterCommand.cs
- src/Emulator/Main/Peripherals/CPU/ICpuSupportingGdb.cs
- src/Emulator/Peripherals/Peripherals/CPU/TranslationCPU.cs
In this [message](https://github.com/renode/renode/issues/50#issuecomment-579842875) mentions the need to fully implement the target.xml file on GDB, so that the RISC-V processors can report the specific CRS records. I needed to implement this functionality to be able to properly debug a Cortex-M processor. In this pull request I propose the solution that I implemented to correct it and add it to the project.
> 50 gdb support specific features

- src/Emulator/Peripherals/Peripherals.csproj
- src/Emulator/Peripherals/Peripherals/GPIOPort/LPC43xx_GPIO.cs
- src/Emulator/Peripherals/Peripherals/Miscellaneous/SevenSegmentsDisplay.cs
- src/Emulator/Peripherals/Test/PeripheralsTests/LPC43xx_GPIO_Test.cs
- src/Emulator/Peripherals/Test/PeripheralsTests/PeripheralsTests.csproj
The GPIO port of the NXP LPC43xx processors and a multiplexed seven segments display are implemented, necessary to be able to add the EDU-CIAA-NXP board that uses these devices.
> 130 add edu ciaa nxp board

- src/UI/CommandLineInterface.cs
- src/UI/Options.cs
This adds `-v|--version` to the Renode command line interface. It prints the version to stdout and directly exits.
Fixes https://github.com/renode/renode/issues/154.
> [#154] add version option

- src/Emulator/Peripherals/Peripherals/Timers/NRF52840_RTC.cs
Clean PR, followup of https://github.com/renode/renode-infrastructure/pull/24
This PR add's the missing rtc CLEAR TASK function for NRF52
> #158: implement task clear

- src/Emulator/Cores/RiscV/IbexRiscV32.cs
- src/Emulator/Cores/cores-riscv.csproj
This is in reference to: https://github.com/renode/renode-infrastructure/pull/33
This uses sets vectored interrupts.
> Add Ibex 32-bit RISC-V core.

- src/Emulator/Cores/RiscV/OpenTitan_PlatformLevelInterruptController.cs
- src/Emulator/Cores/RiscV/PLIC/PlatformLevelInterruptControllerBase.cs
- src/Emulator/Cores/cores-riscv.csproj
Rebased upon recent PLIC changes.
Substituted Context for Target where necessary.
Remove reference to priorities.
Passes dif_plic_sanitytest_sim_verilator.elf from OpenTitan.
> OpenTitan PLIC: Add PLIC to support OpenTitan.

- src/Emulator/Peripherals/Peripherals/UART/EFR32_USART.cs
This toggles transferCompleteFlag in asynchronous mode. I've made sure that the register value is updated before the interrupt is raised.
Fixes https://github.com/renode/renode/issues/155
> [#155] efr32_usart: set flag in async mode

- src/Emulator/Peripherals/Peripherals/SPI/OpenTitan_SpiHost.cs
- The TXQD/RXQD/CMDQD fields in the STATUS register were returning the count of 16-bit values in the FIFO, but should return the count of 32-bit values (see: https://opentitan.org/book/hw/ip/spi_host/doc/registers.html#status--cmdqd)
- Additionally, return early in WriteByte/WriteWord/WriteDoubleWord to squelch a lot of warning noise.
> [FIX] Opentitan_SpiHost: Fix TXQD/RXQD/CMDQD

- src/Emulator/Peripherals/Peripherals/GPIOPort/MiV_CoreGPIO.cs
In order to run tests using the MiV_CoreGPIO peripheral it is required that the OUTBUFF tag has both read and write functionality. Currently if only has the write functionality as is using a tag. In order to allow for both read and write functionality it is necessary to change this tag to a flag.
> 526-MiV_CoreGPIO Adding Readback for OUTBUFF

- src/Emulator/Peripherals/Peripherals/UART/MiV_CoreUART.cs
In order to run tests using the MiV_CoreUART peripheral it is required that bit "0" of the control register has both read and write functionality. Currently if only has the write functionality as is using a tag. In order to allow for both read and write functionality it is necessary to change this tag to a flag.
Signed-by: Eoin Dickson <Eoin.dickson@microchip.com>
> 527-MiV_CoreUART-Added-Register-Readback1

- src/Emulator/Peripherals/Peripherals/Timers/MiV_CoreTimer.cs
MiV_CoreTimer has two modes One-shot and Continuous. When operating in One-shot mode the timer should count down from its initial value and stop. When given an initial value it should reload meaning it should restart counting down from the given number. Currently it will not start counting down for a second time after being set with an initial value.
> 528-MiV_CoreTimer Added Reload for OneShot Mode

- src/Emulator/Peripherals/Peripherals/Miscellaneous/MPFS_DDRMock.cs
This module needs to supply more expected return values for training to complete successfully.
Also took the opportunity to add a 'signature' register, which the software can use to choose to skip training. Training has no impact in Renode and takes several minutes to complete - so an option to skip it is merited.
Issue Reproduction template uses an example from the Microchip Baremetal examples repo - https://github.com/polarfire-soc/polarfire-soc-bare-metal-examples/tree/main/driver-examples/mss/mss-mmuart/mpfs-mmuart-interrupt
https://github.com/econnellmc/renode-issue-reproduction-template/tree/538-DDR_Training-PASS
I have included the .elf file in the reproduction repo.
Failing commit - https://github.com/econnellmc/renode-issue-reproduction-template/actions/runs/6784210479
Passing …
> 538 - Fixed issues with DDR Training

- src/Emulator/Peripherals/Peripherals/CRC/STM32F4_CRC.cs
The STM32F4 CRC engine uses the MPEG2 polynomial and configuration. This is different from most other CRC engines, and is somewhat surprising.
This patch fixes https://github.com/renode/renode/issues/585
> STM32F4_CRC: use correct CRC data

- src/Emulator/Peripherals/Peripherals/Miscellaneous/STM32_PWR.cs
The DBP flag disables low-power protection. This field has been observed in the wild to need to be writable for software to boot.
Make this field an actual flag rather than assuming it is unsettable.
> peripherals: stm32_pwr: support DBP flag

- src/Emulator/Peripherals/Peripherals/Miscellaneous/STM32_PWR.cs
After modifying VOS flag in PWR_CR register it is expected to set VOSRDY flag in PWR_CSR register
> [#602] STM32_PWR. Updating VOSRDY flag after VOS initialization

- src/Emulator/Peripherals/Peripherals/SPI/GenericSpiFlash.cs
- src/Emulator/Peripherals/Peripherals/SPI/Macronix_MX25R.cs
The Macronix MR25R external flash does an AND operation when writing data.
When the memory area is not erased prior writing this will lead to a verification error (done by test FW).
See the following screenshot of a real hardware output.
This PR implements the same behaviour for the peripheral.
> Fix: Macronix MX25R write with AND operation

- src/Emulator/Peripherals/Peripherals.csproj
- src/Emulator/Peripherals/Peripherals/CRC/STM32F0_CRC.cs
- src/Emulator/Peripherals/Peripherals/CRC/STM32WBA_CRC.cs
- src/Emulator/Peripherals/Peripherals/CRC/STM32_CRCBase.cs
Basically the same implementation as STM32F0_CRC
Only difference: size of IndependentData register 8 -> 32
Usage:
/* repl file */
crc: CRC.STM32WBA_CRC @ sysbus 0x40023000
configurablePoly: true
> Feature: STM32WBA5x CRC implementation

- src/Emulator/Extensions/Utilities/USBIP/USBIPServer.cs
Match with linux kernel define of enum usb_device_speed
> USBIPServer: Fix USBSpeed enum value

- src/Emulator/Extensions/Utilities/USBIP/USBIPServer.cs
Since the first descriptor may not be an InterfaceDescriptor, we should move the while-loop to the beginning to correctly skip to the next InterfaceDescriptor
> USBIPServer: Fix multi-interface descriptor parsing logic

- src/Emulator/Extensions/Utilities/USBIP/USBIPServer.cs
Currently urbHeader is a member of class USBIPServerExtensions, so the reply URB header may use a updated wrong sequence number in resultCallback. So we have to create a local copy to capture the proper urbHeader.
> USBIPServer: Fix URB reply header reference for HandleSetupPacket

- src/Emulator/Extensions/Utilities/USBIP/USBIPServer.cs
- src/Emulator/Main/Peripherals/USB/USBDeviceCore.cs
- src/Emulator/Peripherals/Peripherals/SPI/MAX3421E.cs
- src/Emulator/Peripherals/Peripherals/USB/MPFS_USB.cs
DeviceToHost and HostToDevice endpoints can share a same endpoint number, so it is better to distinguish an endpoint by both number and direction.
> USBDeviceCore: Add direction parameter for GetEndpoint

- src/Emulator/Cores/Arm-M/NVIC.cs
The spec indicates that setting the reload value to zero should cause the timer to disable upon the next expiration.
This change also fixes a bug where the countFlag should be cleared writing to the current value register.
> Fixing systick timer when setting reload value to zero.

- src/Emulator/Cores/Arm-M/CortexM.cs
- src/Emulator/Cores/Arm-M/NVIC.cs
Support for ARM Cortex-M SLEEPONEXIT flag.
This goes with changes in the tlib repo as well: https://github.com/antmicro/tlib/pull/18
> Update ARM and NVIC models for Sleep-on-exit flag support

- src/Emulator/Main/Utilities/Binding/NativeBinder.cs
ModuleBuilder.GetType throws an exception when "[]" is in the type name but Array seems to be okay.
> Work around ModuleBuilder.GetType exception

- src/Emulator/Peripherals/Peripherals/I2C/STM32F7_I2C.cs
It looks like the NBYTES and START bit should be allowed to change simultaneously. Otherwise even standard STM32 HAL logic causes this error.
Reference manual says that NBYTES cannot be change only if START is already set:
> STM32F7_I2C: Fix error message condition for NBYTES change when START is set
